### ISSUE TITLE
'authentication' or 'auth'

### ISSUE THREAD

**Issue by sonycamera** [feathersjs/feathers-authentication-hooks#13]
To get the authentication options, some hooks call hook.app.get('authentication') and others call  hook.app.get('auth').  e.g,
`options = Object.assign({}, defaults, hook.app.get('authentication'), options);`
in following hooks:
has-role-or-restrict.js,
associate-current-user.js,
restrict-to-owner.js,
query-with-current-user.js
and 
`options = Object.assign({}, defaults, hook.app.get('auth'), options);`
in following hooks:
restrict-to-roles.js,
owner-or-restrict-changes.js

But in feathers-authentication plugin, it just set('auth', options). Is this(using key 'authentication') a bug?

**Comment by marshallswain** [comment]
I'm pretty sure it's a bug.  We want the defaults to match the generator.
