### ISSUE TITLE
hook.app.get('authentication') might be a problem.

### ISSUE THREAD

**Issue by MHerszak** [feathersjs/feathers-authentication-hooks#15]
Hi,

I was wondering what hook.app.get('authentication') is supposed to load. I am guessing you want to check for the configuration for authentication. See, I call it auth and not 'authentication'. Should I rename mine to 'authentication', too? Is that what you guys are shooting for?

I checked feathers-authentication and you actually name it ```app.set('auth', options);``` should it be changed in this package or are you going to rename 'authentication'?

**Comment by marshallswain** [comment]
The change from `auth` to `authentication` should have happened in the Auk release, but was missed.  This is slated for the next release.
