### ISSUE TITLE
Hook "restrictToOwner" looses context (this) when wrapped

### ISSUE THREAD

**Issue by nikolakanacki** [feathersjs/feathers-authentication-hooks#17]
## The Problem:
When wrapping the `restrictToOwner` hook inside an `iff` hook provided by the `feathers-hooks-common` module, `this` context gets lost and the function errors out:
```
error:  TypeError: this.get is not a function
  Object.<anonymus> (.../feathers-authentication-hooks/lib/restrict-to-owner.js:51:17)
```

## Example:
```javascript
const authHooks = require('feathers-authentication-hooks');
const hooks = require('feathers-hooks-common');

const isAdmin = (hook) => { /* some custom sync logic, returns a boolean */ };

module.exports = {
  before: {
    get: [
      hooks.iff(hooks.isProvider('external'), [
        hooks.iff(hooks.isNot(isAdmin), [
          authHooks.restrictToOwner(),
        ]),
      ]),
    ],
  },
};
```

## Considerations:
Javascript caller context (keyword `this`) is confusing enough. Relying on `this` in "non-class-method" functions is considered bad practice since the ES6 classes and arrow functions arrived to save the day.

Moreover, this function should not rely on `this` to begin with since the called service (which it obviously expects to find under `this`) can easily be obtained from the provided `hook` object (`hook.service`).

## Resolution
If there are no further objections to this issue I'd like to send a quick pr to wrap this up.

**Comment by eddyystop** [comment]
@marshall @daffl ^^^
