### ISSUE TITLE
The documentation link on the README is broken

### ISSUE THREAD

**Issue by brenmcnamara** [feathersjs/feathers-authentication-hooks#6]
The link in the README file to the documentation gives a 404 error.

**Reproduce**: Click on the link named "documentation" in README.md

**Comment by marshallswain** [comment]
Thanks @brenmcnamara.  This will be resolved as soon as the Auk docs are merged to master.  We'll leave it as is, for now, but the correct link until then is https://auk.docs.feathersjs.com/api/authentication/hooks.html

**Comment by brenmcnamara** [comment]
Sounds good! Thanks for the quick response :)

**Comment by gustojs** [comment]
Psst, we're on Buzzard now and the link seems to be broken again.
