### ISSUE TITLE
restrictToOwner 'as' option 

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-authentication-hooks#7]
In docs, it is said that, for `the restrictToOwner` hook,

> For find method calls and patch, update and remove of many (with id set to null), the queryWithCurrentUser hook will be called to limit the query to the current user.

However, `restrictToOwner` has a `ownerField` option, whereas `queryWithCurrentUser` wants a `as` option.

When calling `queryWithCurrentUser`, `restrictToOwner` shouldn't rename the `ownerField` options `as` ?

**Comment by daffl** [comment]
It does indeed, that's what happens when you run your tests only against the defaults. Thanks for the catch, fixed in v0.1.1

**Comment by daffl** [comment]
Do we need to update anything in the docs? I think it makes sense now right?

**Comment by sylvainlap** [comment]
No, no need to update the docs.
Thanks !
